#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - HARDWARE - BUZZER                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
# nspanel_esphome_core.yaml:
#   api.actions.notification_show
###############################

---
api:
  id: !extend api_server
  actions:
    - action: rtttl_play
      variables:
        tone: string  # The RTTTL string for the melody to be played. It should follow the RTTTL format, including the melody's name, default settings, and a sequence of notes.
      then:
        - lambda: |-
            if (!id(is_uploading_tft)) buzzer->play(tone);

output:
  # Buzzer output
  - id: buzzer_out
    platform: ledc
    pin:
      number: 21

##### ENABLE RINGTONE MUSIC SUPPORT #####
rtttl:
  id: buzzer
  output: buzzer_out

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          ESP_LOGCONFIG("script.boot_progress_dump", " - HW Buzzer:            %s", is_boot_step_completed(BOOT_STEP_HW_BUZZER) ? "Completed" : "PENDING");

  - id: !extend boot_sequence
    then:
      - lambda: |-
          boot_progress->execute(BOOT_STEP_HW_BUZZER);

  - id: !extend page_boot
    then:
      - lambda: |-
          if (notification_sound->state) {
            boot_log->execute("Boot", "Play boot sound");
            buzzer->play("two short:d=4,o=5,b=100:16e6,16e6");
          }
...
