#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - HARDWARE - BUZZER                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
# nspanel_esphome_core.yaml:
#   api.actions.notification_show
###############################

---
substitutions:
  BOOT_STEP_HW_BUZZER: '1UL << 4'
  tone_touch_enable: 'true'
  tone_touch_press: "Touch:d=16,o=5,b=180:g"
  tone_touch_release: "Release:d=32,o=5,b=180:g,g"

api:
  actions:
    - action: rtttl_play
      variables:
        tone: string  # The RTTTL string for the melody to be played. It should follow the RTTTL format, including the melody's name, default settings, and a sequence of notes.
      then:
        - rtttl.stop
        - rtttl.play: !lambda return tone;

display:
  - id: !extend disp1
    on_touch:
      then:
        - if:
            condition:
              - lambda: return (${tone_touch_enable});
            then:
              - if:
                  condition:
                    - lambda: return touch_event;
                  then:
                    - rtttl.play: ${tone_touch_press}
                  else:
                    - rtttl.play: ${tone_touch_release}

output:
  # Buzzer output
  - id: buzzer_out
    platform: ledc
    pin:
      number: 21

##### ENABLE RINGTONE MUSIC SUPPORT #####
rtttl:
  id: buzzer
  output: buzzer_out

script:
  - id: !extend boot_progress_dump
    then:
      - script.execute:
          id: boot_progress_dump_item
          step: ${BOOT_STEP_HW_BUZZER}
          step_name: HW Buzzer

  - id: !extend boot_sequence
    then:
      - script.execute:
          id: boot_progress
          step: ${BOOT_STEP_HW_BUZZER}
          step_name: HW Buzzer

  - id: !extend page_boot
    then:
      - if:
          condition:
            - switch.is_on: notification_sound
          then:
            - script.execute:
                id: boot_log
                category: Boot
                log_message: Play boot sound
            - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"
...
