#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Home                                                                  #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
###############################

---
globals:
  ##### Chips #####
  - id: home_chip_font_id
    type: uint8_t
    restore_value: true
    initial_value: '7'

  #### Custom buttons ####
  - id: home_custom_buttons_font_id
    type: uint8_t
    restore_value: true
    initial_value: '8'

script:
  - id: chip_font
    mode: restart
    parameters:
      chip_font: uint8_t
      boot: bool
    then:
      - lambda: |-
          if (boot or chip_font != id(home_chip_font_id)) {
            id(home_chip_font_id) = chip_font;
            disp1->set_component_font("home.wifi_icon", chip_font);
            // Chips icon size
            disp1->set_component_font("home.chip_relay1", chip_font);
            disp1->set_component_font("home.chip_relay2", chip_font);
            disp1->set_component_font("home.chip_climate", chip_font);

            for (int i = 1; i <= 7; ++i) {
              disp1->send_command_printf("home.chip%02d.font=%" PRIu8, i, chip_font);
            }
          }

  - id: custom_buttons_font
    mode: restart
    parameters:
      custom_buttons_font: uint8_t
      boot: bool
    then:
      - lambda: |-
          if (boot or custom_buttons_font != id(home_custom_buttons_font_id)) {
            id(home_custom_buttons_font_id) = custom_buttons_font;
            disp1->set_component_font("home.bt_notific", id(home_custom_buttons_font_id));
            disp1->set_component_font("home.bt_qrcode", id(home_custom_buttons_font_id));
            disp1->set_component_font("home.bt_entities", id(home_custom_buttons_font_id));
            for (int i = 1; i <= 7; ++i) {
              disp1->send_command_printf("home.button%02d.font=%" PRIu8, i, id(home_custom_buttons_font_id));
            }
          }

  - id: !extend boot_sequence
    then:
      - lambda: |-
          boot_log->execute("Boot", "Set Home page elements");
          // Chips icon size
          chip_font->execute(id(home_chip_font_id), true);

  - id: !extend page_changed
    then:
      - lambda: |-
          if (current_page->state == "home") page_home->execute();

  - id: page_home
    mode: restart
    then:  # There's nothing to do so far

  - id: !extend set_var_int
    then:
      - lambda: |-
          if (component == "chip_font") chip_font->execute(val, false);
          else if (component == "custom_buttons_font") custom_buttons_font->execute(val, false);

  - id: !extend stop_all
    then:
      - script.stop: chip_font
      - script.stop: custom_buttons_font
      - script.stop: page_home
...
