#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Cover                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
script:
  - id: !extend event_from_display
    then:
      - lambda: |-
          if (page == "cover") {
            if (key == "position") ha_call_action->execute("cover.set_cover_position", key.c_str(), value.c_str(), detailed_entity->state.c_str());
            else ha_call_action->execute(("cover." + key).c_str(), "", "", detailed_entity->state.c_str());
          }

#   - id: !extend page_changed
#     then:
#       - lambda: |-
#           if (current_page->state == "cover") page_cover->execute();

#   - id: page_cover
#     mode: restart
#     then:  # There's nothing here so far

#   - id: !extend stop_all
#     then:
#       - script.stop: page_cover
...
