#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Blank                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_BLANK: '1UL << 27'

script:
  - id: !extend boot_progress_dump
    then:
      - script.execute:
          id: boot_progress_dump_item
          step: ${BOOT_STEP_PAGE_BLANK}
          step_name: Page Blank

  - id: !extend boot_sequence
    then:
      - script.execute:
          id: boot_progress
          step: ${BOOT_STEP_PAGE_BLANK}
          step_name: Page Blank

  - id: page_blank
    mode: restart
    then:
      - script.execute:
          id: send_command
          cmd: 'tm_esphome.en=0'
      - script.execute:
          id: set_component_text
          component: esp_version
          text: "FW: ${version}"  # ESPHome version
      - if:
          condition:
            - lambda: |-
                #ifdef ARDUINO
                return true;
                #else
                return false;
                #endif
          then:
            - script.execute:
                id: set_component_text
                component: framework
                text: Arduino
          else:
            - script.execute:
                id: set_component_text
                component: framework
                text: ESP-IDF

  - id: !extend page_changed
    then:
      - if:
          condition:
            - text_sensor.state:
                id: current_page
                state: blank
          then:
            - script.execute: page_blank

  - id: !extend stop_all
    then:
      - script.stop: page_blank
...
