#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - QRCODE                                                                     #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
api:
  actions:
    # Dynamically displays QR codes on the ESPHome UI for sharing information such as WiFi passwords or website links.
    - action: qrcode
      variables:
        title: string   # Heading or title for the QR code, offering context or instructions.
        qrcode: string  # Data or URL to be encoded into the QR code.
        show: bool      # Flag to immediately display the QR code page upon action invocation.
      then:
        - lambda: |-
            id(qrcode_string) = qrcode;
            delay(10*disp1->queue_size()+tf_uart->available());
            set_component_visibility->execute("home", "bt_qrcode", !(id(qrcode_string).empty()));
            delay(10*disp1->queue_size()+tf_uart->available());
            disp1->set_component_text("qrcode.qrcode_label", title.c_str());
            delay(10*disp1->queue_size()+tf_uart->available());
            if (show) goto_page->execute("qrcode");
            boot_progress->execute(BOOT_STEP_PAGE_QRCODE, "Page QRcode - Action");

globals:
  - id: qrcode_enabled
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: qrcode_string
    type: std::string
    restore_value: false
    max_restore_data_length: 254
    initial_value: '""'

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          ESP_LOGCONFIG("script.boot_progress_dump", " - Page QR Code:         %s", is_boot_step_completed(BOOT_STEP_PAGE_QRCODE) ? "Completed" : "PENDING");

  - id: !extend page_changed
    then:
      - if:
          condition:
            - text_sensor.state:
                id: current_page
                state: qrcode
          then:
            - script.execute: page_qrcode

  - id: !extend page_home
    then:
      - script.execute:
          id: set_component_visibility
          page: home
          component_id: bt_qrcode
          show: !lambda return id(qrcode_enabled);

  # Load the QRCode page
  - id: page_qrcode
    mode: restart
    then:
      - lambda: |-
          if (!id(qrcode_string).empty()) {
            disp1->qrcode(25, 25, id(qrcode_string).c_str());
          }

  - id: !extend set_var_bool
    then:
      - lambda: |-
          if (component == "qrcode_enabled") {
            id(qrcode_enabled) = val;
            delay(10*disp1->queue_size()+tf_uart->available());
            set_component_visibility->execute("home", "bt_qrcode", id(qrcode_enabled));
            if (!val) boot_progress->execute(BOOT_STEP_PAGE_QRCODE, "Page QRcode - Enabler");
          }

  - id: !extend stop_all
    then:
      - script.stop: page_qrcode
...
