#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page keyb_num                                                              #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_KEYBOARD_NUM: '1UL << 18'

script:
  - id: !extend boot_progress_dump
    then:
      - script.execute:
          id: boot_progress_dump_item
          step: ${BOOT_STEP_PAGE_KEYBOARD_NUM}
          step_name: Page Keyboard (Num)

  - id: !extend boot_sequence
    then:
      - script.execute:
          id: boot_progress
          step: ${BOOT_STEP_PAGE_KEYBOARD_NUM}
          step_name: Page Keyboard (Num)

  - id: !extend event_from_display
    then:
      - lambda: |-
          if (page == "keyb_num") {
            const std::string base_domain = json["base_domain"];
            if (base_domain == "alarm") {
              const std::string code_format = json["code_format"];
              const std::string pin = json["pin"];
              action_call_alarm_control_panel->execute(detailed_entity->state.c_str(), key.c_str(), code_format.c_str(), pin.c_str());
            }
            goto_page->execute(base_domain.empty() ? "home" : base_domain.c_str());
          }

#   - id: !extend page_changed
#     then:
#       - lambda: |-
#           if (current_page->state == "keyb_num") page_keyb_num->execute();

#   - id: page_keyb_num
#     mode: restart
#     then:  # There's nothing here so far

#   - id: !extend stop_all
#     then:
#       - script.stop: page_keyb_num
...
