#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - ALARM PAGE                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
###############################

---
api:
  id: !extend api_server
  actions:
    # Utilities group refresh
    - action: utilities_group_refresh
      variables:
        group_id: string
        value1: string
        value2: string
        direction: int
        constructor: bool
      then:
        - lambda: |-
            if (!id(is_uploading_tft) and !group_id.empty()) {
              uint8_t id = findUtilitiesGroupIndex(group_id.c_str());
              if (id != UINT8_MAX) {
                // Update Value 1
                if (!value1.empty() and
                    (constructor or strcmp(value1.c_str(), UtilitiesGroups[id].value1) != 0)) {
                  copyStringToCharArray(UtilitiesGroups[id].value1, value1);
                  disp1->set_component_text(group_id.c_str(), value1.c_str());
                }

                // Update Value 2
                if (!value2.empty() and
                    (constructor or strcmp(value2.c_str(), UtilitiesGroups[id].value2) != 0)) {
                  copyStringToCharArray(UtilitiesGroups[id].value2, value2);
                  disp1->set_component_text((group_id + "b").c_str(), value2.c_str());
                }

                // Update direction
                if (group_id != "grid" and !isnan(direction) and
                    (constructor or direction != UtilitiesGroups[id].direction)) {
                  UtilitiesGroups[id].direction = direction;
                  disp1->set_component_value((group_id + "_line_d").c_str(), direction);
                }
              }
            }

esphome:
  includes:
    - libraries/utilities

script:
  - id: !extend page_changed
    then:
      - lambda: |-
          if (current_page->state == "utilities") page_utilities->execute();

  - id: page_utilities
    mode: restart
    then:
      - lambda: if (UtilitiesGroups == nullptr) resetUtilitiesGroups();

  - id: !extend stop_all
    then:
      - lambda: |-
          cleanupUtilitiesGroups();
      - script.stop: page_utilities
...
