#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - PAGE - NOTIFICATION                                                        #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
api:
  id: !extend api_server
  actions:
    # This action removes any displayed notifications from the screen, helping to keep the user interface clean and focused on its primary functions.
    - action: notification_clear
      then:
        - lambda: |-
            if (!id(is_uploading_tft)) {
              if (current_page->state == "notification") goto_page->execute("home");
              notification_label->publish_state("");
              notification_text->publish_state("");
              notification_unread->turn_off();
              set_component_visibility->execute("home", "bt_notific", false);
            }

    # Displays a notification message on the screen, useful for alerts or informational updates.
    - action: notification_show
      variables:
        label: string    # Title or label for the notification, displayed in a prominent format.
        message: string  # Detailed message or content of the notification. Include `\r` to insert a line break, allowing for custom formatting.
      then:
        - lambda: |-
            if (!id(is_uploading_tft)) {
              set_component_visibility->execute("home", "bt_notific", true);
              goto_page->execute("notification");
              timer_reset_all->execute();
              disp1->set_component_text("notification.notifi_label", label.c_str());
              display_wrapped_text->execute("notification", "notifi_text01", message.c_str(), display_mode->state == 2 ? 23 : 32);
              notification_label->publish_state(label.c_str());
              notification_text->publish_state(message.c_str());
              notification_unread->turn_on();
              if (notification_sound->state) buzzer->play("two short:d=4,o=5,b=100:16e6,16e6");
            }

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (page_id == 16) {  // Page Notification
              switch (component_id) {
                case 7:  // bt_accept
                  if (!touch_event) {  // Release
                    notification_label->publish_state("");
                    notification_text->publish_state("");
                    notification_unread->turn_off();
                    goto_page->execute("home");
                    set_component_visibility->execute("home", "bt_notific", false);
                  }
                break;
                case 8:  // bt_clear
                  if (!touch_event) {  // Release
                    notification_unread->turn_off();
                    goto_page->execute("home");
                  }
                break;
              }
            }

script:
  - id: !extend page_changed
    then:
      - lambda: |-
          if (current_page->state == "notification") page_notification->execute();

  - id: page_notification
    mode: restart
    then:
      - lambda: |-
          disp1->set_component_text("notification.notifi_label", notification_label->state.c_str());
          display_wrapped_text->execute("notification", "notifi_text01", notification_text->state.c_str(), display_mode->state == 2 ? 23 : 32);

  - id: !extend stop_all
    then:
      - script.stop: page_notification

switch:
  ##### Notification unread #####
  - name: Notification unread
    platform: template
    id: notification_unread
    entity_category: config
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      lambda: |-
        esphome::api::CustomAPIDevice ha_event;
        ha_event.fire_homeassistant_event("esphome.nspanel_ha_blueprint", {
          {"device_name", device_name->state.c_str()},
          {"esphome_version", "${version}"},
          {"type", "notification_changed"},
          {"component", "notification_unread"},
          {"action", "turn_on"}
        });
    on_turn_off:
      lambda: |-
        esphome::api::CustomAPIDevice ha_event;
        ha_event.fire_homeassistant_event("esphome.nspanel_ha_blueprint", {
          {"device_name", device_name->state.c_str()},
          {"esphome_version", "${version}"},
          {"type", "notification_changed"},
          {"component", "notification_unread"},
          {"action", "turn_off"}
        });

  ##### Notification sound #####
  - name: Notification sound
    platform: template
    id: notification_sound
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - id: notification_label
    name: Notification Label
    platform: template
    on_value:
      lambda: |-
        esphome::api::CustomAPIDevice ha_event;
        ha_event.fire_homeassistant_event("esphome.nspanel_ha_blueprint", {
          {"device_name", device_name->state.c_str()},
          {"esphome_version", "${version}"},
          {"type", "notification_changed"},
          {"component", "notification_label"},
          {"action", "new_value"}
        });

  - id: notification_text
    name: Notification Text
    platform: template
    on_value:
      lambda: |-
        esphome::api::CustomAPIDevice ha_event;
        ha_event.fire_homeassistant_event("esphome.nspanel_ha_blueprint", {
          {"device_name", device_name->state.c_str()},
          {"esphome_version", "${version}"},
          {"type", "notification_changed"},
          {"component", "notification_text"},
          {"action", "new_value"}
        });

...
