#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Fan                                                                   #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (page_id == 22) {  // Page Fan
              switch (component_id) {
                case 11:  // bt_oscillate
                  if (!touch_event) {  // Release
                    ha_call_action->execute("fan.oscillate", "oscillating", "toggle", detailed_entity->state.c_str());
                  }
                  break;
                case 12:  // power_button
                  if (!touch_event) {  // Release
                    ha_call_action->execute("fan.toggle", "", "", detailed_entity->state.c_str());
                  }
                  break;
              }
            }

script:
  - id: !extend event_from_display
    then:
      - lambda: |-
          if (page == "fan") {
            if (key == "stop" or value == "0") ha_call_action->execute("fan.turn_off", "", "", detailed_entity->state.c_str());
            else ha_call_action->execute("fan.turn_on", key.c_str(), value.c_str(), detailed_entity->state.c_str());
          }

#   - id: !extend page_changed
#     then:
#       - lambda: |-
#           if (current_page->state == "fan") page_fan->execute();

#   - id: page_fan
#     mode: restart
#     then:  # There's nothing here so far

#   - id: !extend stop_all
#     then:
#       - script.stop: page_fan
...
